name: OneChance
main: com.ptibiscuit.onechance.OneChance
version: 0.6
depend: [PluginsBaker]
description: Extreme survivals, muhahahaha !
authors:
- Ptibiscuit
commands:
 ocbuy:
  description: Achete une vie.
  usage: /ocbuy